python scripts/preprocess.py
python scripts/finetune.py
python scripts/evaluate_toxicity.py
python scripts/evaluate_perspective.py
python scripts/askgpt4_toxic.py
python scripts/evaluate_persona.py 
python scripts/evaluate_speed.py
python scripts/evaluate_sentiment.py
python scripts/askgpt4_sentiment.py
python scripts/postprocess.py